name: Release

on:
  release:
    types: [published]

jobs:
  build13:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Download upload_url
      uses: actions/download-artifact@v8
      with:
        name: upload_url
        path: upload_url
    - name: Set release version
      run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
    - uses: actions/checkout@v6
    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"
    - name: Make packaging script executable
      run: chmod +x ./package13.sh
    - name: Build adapter
      run: |
        ADDON_ARCH=linux-arm64 ./package13.sh
      shell: bash
    - name: List after container
      run: |
        ls -lh
      shell: bash
    - name: Find after container
      run: |
        find . -name '*.tar.gz'
      shell: bash
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: matter-adapter-*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

        
