name: Release

on:
  release:
    types: [created]

jobs:
  get-release:
    runs-on: ubuntu-latest
    steps:
    - name: Get Release
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Dump upload url to file
      run: echo '${{ steps.get_release.outputs.upload_url }}' > upload_url
    - name: Upload upload_url
      uses: actions/upload-artifact@v3
      with:
        name: upload_url
        path: upload_url

  build:
    needs: get-release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      id: build_image
      with:
        base_image: raspios_lite_arm64:latest
        commands: |
            uname -a
    - name: Download upload_url
      uses: actions/download-artifact@v3
      with:
        name: upload_url
        path: upload_url
    - name: Set upload_url
      run: echo "UPLOAD_URL=$(cat upload_url/upload_url)" >> $GITHUB_ENV
    - name: Set release version
      run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Use Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    #- name: update pip
    #  run: python3 -m pip install --upgrade pip
    - name: Make build script executable
      run: chmod +x ./build.sh
    - name: Make packaging script executable
      run: chmod +x ./package.sh
    - name: Build adapter
      run: |
        ADDON_ARCH="linux-arm64" ./package.sh "linux-arm64" "python" "3.9"
      shell: bash
      
    - name: Upload Release Asset tgz
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        #upload_url: ${{ github.event.release.upload_url }}
        upload_url: ${{ env.UPLOAD_URL }}
        asset_path: matter-adapter-${{ env.RELEASE_VERSION }}-linux-arm64-v3.9.tgz
      
    - name: Upload Release Asset shasum
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        #upload_url: ${{ github.event.release.upload_url }}
        upload_url: ${{ env.UPLOAD_URL }}
        asset_path: matter-adapter-${{ env.RELEASE_VERSION }}-linux-arm64-v3.9.tgz.sha256sum

